appointment/urls.py
from django.urls import path

from appointment.views import IndexView, IndexViewOld, DetailView, CreateFromPoll, \
    CancelAppointmentView, PollInvitationCreateView, PollInvitationDeleteView

app_name = 'appointment'
urlpatterns = [
    path('home/', IndexView.as_view(), name='home'),
    path('cancel-appointment/<int:pk>/', CancelAppointmentView.as_view(),
         name='cancel-appointment'),
    path('old/', IndexViewOld.as_view(), name='old'),
    path('<int:pk>/', DetailView.as_view(), name='detail'),
    path('from-polls/', CreateFromPoll.as_view(), name='create-from-poll'),
    path('poll-invitations/create/<int:pk>/', PollInvitationCreateView.as_view(),
         name='create-poll-invitation'),
    path('poll-invitations/delete/<int:pk>/', PollInvitationDeleteView.as_view(),
         name='delete-poll-invitation'),
]

jalas/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('appointment/', include('appointment.urls')),
    path('reservation/', include('reservation.urls')),
    path('monitoring/', include('monitoring.urls')),
    prefix_default_language=False)

reservation/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from reservation.views import PollDetailsView, AvailableRoomsView, \
    PollCreateView, VoteCreateView, CancelPollView, CommentsView, \
    AddItem, CommentsViewUpdate, CommentsViewDelete, PollItemDelete, ReplyCreateView

app_name = 'reservation'
urlpatterns = [
    path('polls/<int:pk>/cancel/', CancelPollView.as_view(), name='cancel-poll'),
    path('polls/<int:pk>/comments/', CommentsView.as_view(), name='poll-comments'),
    path('polls/<int:pk>/', PollDetailsView.as_view(), name='poll-details'),
    path('polls/<int:pk>/additem/', AddItem.as_view(), name='add-item'),
    path('polls/new/', PollCreateView.as_view(), name='poll-create'),
    path('<int:pk>/cancel/', PollItemDelete.as_view(), name='poll-item-delete'),
    path('available-rooms/', AvailableRoomsView.as_view()),
    path('<uuid:uuid>/', csrf_exempt(VoteCreateView.as_view()), name='vote-details'),
    path('comment-edit/<int:pk>/', CommentsViewUpdate.as_view(), name='comment-update'),
    path('comment-delete/<int:pk>/', CommentsViewDelete.as_view(), name='comment-delete'),
    path('reply-create/<int:pk>/', ReplyCreateView.as_view(), name='reply-create'),
]

appointment/models.py
import uuid

from django.db import models
from django.template.loader import render_to_string
from django.utils import timezone

from accounts.models import User
from reservation import facade
from reservation.models import Poll, PollItem
from utilities import mail_sender


class Appointment(models.Model):
    poll_item = models.ForeignKey(PollItem, on_delete=models.CASCADE)
    poll = models.OneToOneField(Poll, on_delete=models.CASCADE)
    room_number = models.CharField(max_length=64, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    is_cancelled = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        created = self.pk is None
        super().save(*args, **kwargs)
        if created:
            self._on_create()

    def _on_create(self):
        facade.finalize_poll(self.poll)


class PollInvitation(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4)
    poll = models.ForeignKey('reservation.Poll', on_delete=models.CASCADE,
                             related_name='invitations')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        created = self.pk is None
        super().save(*args, **kwargs)
        if created:
            self._on_create()

    def delete(self, *args, **kwargs):
        self._on_delete()
        return super().delete(*args, **kwargs)

    def _on_create(self):
        if not self.user.invitation_notification:
            return
        rendered_email = render_to_string('emails/poll_invitation.html', context={
            'invitation': self
        })
        mail_sender.send_email('نظرسنجی جلسه', rendered_email, [self.user.email])

    def _on_delete(self):
        if not self.user.invitation_delete_notification:
            return
        rendered_email = render_to_string('emails/invitation_delete_notification.html', context={
            'invitation': self
        })
        mail_sender.send_email('پس گرفتن دعوت', rendered_email, [self.user.email])

appointment/forms.py
import re

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Field
from django import forms
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory, ModelForm

from accounts.models import User
from appointment.models import PollInvitation
from reservation.models import Poll


class PollInvitationAddForm(ModelForm):
    email = forms.EmailField(label='ایمیل')

    def __init__(self, *args, **kwargs):
        poll = kwargs.pop('poll')
        super().__init__(*args, **kwargs)
        self.poll = poll

    def clean_email(self):
        email = self.cleaned_data['email']
        if self.poll.invitations.filter(user__email=email).exists():
            raise ValidationError('در حال حاضر فرد مورد نظر دعوت شده است')
        return email

    def save(self, commit=True):
        email = self.cleaned_data['email']
        user, _ = User.objects.get_or_create(email=email, defaults={
            'username': email
        })
        self.instance.user = user
        return super().save(commit)

    class Meta:
        model = PollInvitation
        fields = ['email']


class PollInvitationForm(ModelForm):
    email = forms.EmailField(label='ایمیل')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        formtag_prefix = re.sub('-[0-9]+$', '', kwargs.get('prefix', ''))

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Field('email'),
                Field('DELETE'),
                css_class='formset_row-{}'.format(formtag_prefix)
            )
        )

    def save(self, commit=True):
        email = self.cleaned_data['email']
        user, _ = User.objects.get_or_create(email=email, defaults={
            'username': email
        })
        self.instance.user = user
        return super().save(commit)

    class Meta:
        model = PollInvitation
        fields = []


PollInvitationFormSet = inlineformset_factory(
    Poll, PollInvitation, form=PollInvitationForm, extra=0, can_delete=True, min_num=2,
    validate_min=True
)

appointment/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic, View
from django.views.generic import CreateView, DeleteView
from rest_framework.status import HTTP_400_BAD_REQUEST

from appointment.forms import PollInvitationAddForm
from appointment.models import Appointment, PollInvitation
from reservation import facade
from reservation.exceptions import LogicException
from reservation.models import PollItem, Poll


class IndexView(PermissionRequiredMixin, generic.ListView):
    template_name = 'appointment/home.html'
    context_object_name = 'object'

    def has_permission(self):
        return self.request.user.is_authenticated

    def get_queryset(self):
        poll_created = Poll.objects.filter(
            creator__username=self.request.user.username,
            appointment__created_at__isnull=True).distinct()
        appointments = Appointment.objects.filter(
            poll_item__date__gt=datetime.now().date()).order_by('poll_item__date')
        poll_invited = PollInvitation.objects.filter(user=self.request.user, vote__isnull=True,
                                                     poll__appointment__isnull=True).distinct()
        return {'poll_created': poll_created,
                'appointment': appointments, 'pollInvited': poll_invited}


class IndexViewOld(generic.ListView):
    template_name = 'appointment/index.html'
    context_object_name = 'object'

    def get_queryset(self):
        appointments = Appointment.objects.filter(
            poll_item__date__lt=datetime.now().date()).order_by(
            'poll_item__date')[:10]
        return {'appointment': appointments}


class DetailView(PermissionRequiredMixin, generic.DetailView):
    model = Appointment
    template_name = 'appointment/detail.html'
    context_object_name = 'appointment'

    def has_permission(self):
        return self.request.user == self.get_object().poll.creator


class CreateFromPoll(LoginRequiredMixin, View):
    model = Appointment

    def post(self, request, *args, **kwargs):
        try:
            room_number = request.POST.get('room_number')
            poll_item = self._extract_poll_item(request)
            self._reserve_room(poll_item, room_number)
            poll_item.poll.refresh_from_db()
            if poll_item.poll.state != 'CANCELLED':
                Appointment.objects.create(
                    poll_item=poll_item,
                    poll=poll_item.poll,
                    room_number=room_number,
                )
        except LogicException as e:
            return JsonResponse(data={'err': e.msg}, status=HTTP_400_BAD_REQUEST)
        return JsonResponse(
            data={'url': reverse('reservation:poll-details', kwargs={'pk': poll_item.poll_id})})

    @staticmethod
    def _extract_poll_item(request):
        poll_item_id = request.POST.get('poll_item')
        poll_item = get_object_or_404(PollItem, id=poll_item_id)
        if poll_item.poll.creator != request.user or hasattr(poll_item.poll, 'appointment'):
            raise PermissionDenied()
        if poll_item.poll.state == 'CANCELLED':
            raise LogicException('این نظرسنجی کنسل شده است')
        poll_item.poll.state = 'RESERVING'
        poll_item.poll.save()
        return poll_item

    def _reserve_room(self, poll_item, room_number):
        facade.reserve_room(
            poll_item.poll.creator.username,
            room_number,
            poll_item.start,
            poll_item.end)


class CancelAppointmentView(PermissionRequiredMixin, View):
    def has_permission(self):
        self.appointment = get_object_or_404(Appointment, pk=self.kwargs['pk'])
        return self.appointment.poll.creator == self.request.user

    def get(self, request, *args, **kwargs):
        self.appointment.is_cancelled = True
        self.appointment.save()
        facade.on_appointment_cancel(self.appointment)
        messages.success(request, 'جلسه لغو شد')
        return HttpResponseRedirect(reverse('reservation:poll-details',
                                            kwargs={'pk': self.appointment.poll_id}))


class PollInvitationCreateView(PermissionRequiredMixin, CreateView):
    form_class = PollInvitationAddForm
    template_name = 'appointment/poll_invitation_create_view.html'

    def get_poll(self):
        return get_object_or_404(Poll, pk=self.kwargs['pk'])

    def has_permission(self):
        return self.get_poll().creator == self.request.user

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['poll'] = self.get_poll()
        return kwargs

    def form_valid(self, form):
        poll = self.get_poll()
        form.instance.poll = poll
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('reservation:poll-details', kwargs={'pk': self.get_poll().id})


class PollInvitationDeleteView(PermissionRequiredMixin, DeleteView):
    model = PollInvitation

    def has_permission(self):
        invitation = get_object_or_404(PollInvitation, pk=self.kwargs['pk'])
        return invitation.poll.creator == self.request.user

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    def get_success_url(self):
        messages.success(self.request, 'کاربر مورد نظر با موفقیت حذف شد')
        return reverse('reservation:poll-details', kwargs={'pk': self.object.poll_id})

templates/appointment/detail.html
{% extends 'base.html' %}
{% block  card_body %}

    {% if error_massage %}
        <p><strong> {{ error_massage }}</strong></p>
    {% endif %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">عنوان جلسه</th>
            <th scope="col">اتاق جلسه</th>
            <th scope="col">زمان شروع</th>
            <th scope="col">زمان پایان</th>
        </tr>
        </thead>
        <tbody>
        <th scope="row">  {{ appointment.poll.title }}</th>
        <th scope="row">  {{ appointment.room_number }}</th>
        <th scope="row">  {{ appointment.poll_item.start_at }}</th>
        <th scope="row">  {{ appointment.poll_item.end_at }}</th>
        </tbody>
    </table>
    <a href="{% url 'reservation:poll-details' appointment.poll.id %}" class="btn btn-info">
        جزئیات نظرسنجی
    </a>
{% endblock %}

templates/appointment/home.html
{% extends 'base.html' %}

{% block card_header %}
    در یک نگاه
{% endblock %}

{% block  card_body %}
    <h4> رویداد های پیش رو</h4>
    {% include 'event.html' with appointments=object.appointment url='appointment:detail' %}


    <h4>نظر سنجی های ایجاد شده</h4>
    {% include 'appointment/list_poll.html' with polls=object.poll_created %}

    <h4>نظر سنجی های نیاز به رای شما دارد</h4>
    <ul>
        {% for invitation in object.pollInvited %}
            <li>
                <a href="{% url 'reservation:vote-details'  invitation.uuid %}">{{ invitation.poll.title }} </a>
            </li>
        {% empty %}
            <li class="text-secondary">نظرسنجی وجود ندارد</li>
        {% endfor %}
    </ul>
    <div class="btn-group" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-outline-success">
            <a class="nav-link" href="{% url 'reservation:poll-create' %}">
                <i class="fa "></i>
                ایجاد نظرسنجی
            </a>
        </button>
        <button type="button" class="btn btn-outline-secondary">
            <a class="nav-link" href="{% url 'appointment:old' %}">
                <i class="fa "></i>
                نمایش ۱۰ جلسه اخیر
            </a>
        </button>

    </div>

{% endblock %}

templates/appointment/index.html
{% extends 'base.html' %}
{% block  card_body %}

    {% if object.appointments %}
        <h1>رویداد های گذشته</h1>
        {% include 'event.html' with appointments=object.appointments  url='appointment:detail' %}
    {% else %}
        <h1> جلسه ای موجود نمی باشد</h1>
    {% endif %}




    <div class="btn-group" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-outline-success">
            <a class="nav-link" href="{% url 'reservation:poll-create' %}">
                <i class="fa "></i>
                ایجاد نظرسنجی برای جلسه
            </a>
        </button>
        <button type="button" class="btn btn-outline-secondary">
            <a class="nav-link" href="{% url 'appointment:home' %}">
                <i class="fa "></i>
                بازگشت به خانه
            </a>
        </button>

    </div>
{% endblock %}

templates/appointment/list_poll.html
{% block listPoll %}
    {{ polls.0.poll.title }}
    <ul>
        {% for poll in polls %}
            <li>
                <a href="{% url 'reservation:poll-details'  poll.id %}">{{ poll.title }} </a>
            </li>
        {% empty %}
            <li class="text-secondary">نظرسنجی وجود ندارد</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/appointment/pollCreate.html
{% extends 'base.html' %}
{% block  card_body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panle panel-default">
                    <div class="panel-body">
                        <h3>ایجاد جلسه</h3>
                        {% if error_massage %}
                            <p><strong>{{ error_massage }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success"> submit</button>


                                </div>

                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/appointment/poll_invitation_create_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block card_header %}
    دعوت از فرد جدید
{% endblock %}

{% block card_body %}
    <form method="post" class="mb-4">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">اعمال تغیرات</button>
    </form>
{% endblock %}