accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts.views import UserFormView, LoginView, NotificationPolicyView

app_name = 'accounts'
urlpatterns = [
    path('signup/', UserFormView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('notification-policy/', NotificationPolicyView.as_view(), name='notification-policy')
]

appointment/urls.py
from django.urls import path

from appointment.views import IndexView, IndexViewOld, DetailView, CreateFromPoll, \
    CancelAppointmentView, PollInvitationCreateView, PollInvitationDeleteView

app_name = 'appointment'
urlpatterns = [
    path('home/', IndexView.as_view(), name='home'),
    path('cancel-appointment/<int:pk>/', CancelAppointmentView.as_view(),
         name='cancel-appointment'),
    path('old/', IndexViewOld.as_view(), name='old'),
    path('<int:pk>/', DetailView.as_view(), name='detail'),
    path('from-polls/', CreateFromPoll.as_view(), name='create-from-poll'),
    path('poll-invitations/create/<int:pk>/', PollInvitationCreateView.as_view(),
         name='create-poll-invitation'),
    path('poll-invitations/delete/<int:pk>/', PollInvitationDeleteView.as_view(),
         name='delete-poll-invitation'),
]

jalas/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('appointment/', include('appointment.urls')),
    path('reservation/', include('reservation.urls')),
    path('monitoring/', include('monitoring.urls')),
    prefix_default_language=False)

templates/base.html
{% load static %}

<!doctype html>
<html lang="fa">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#1a1a1a">
    {% block meta_tags %}{% endblock %}
    {% block favicon %}
        <link rel="shortcut icon" href="{% static 'img/ut_logo.png' %}">
    {% endblock %}

    <title>{% block title %}
        جلس | سامانه مدیریت جلسات
    {% endblock %}</title>

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/app.css' %}?v=1.0.3" rel="stylesheet">
    <link href="{% static 'css/awesome-font.min.css' %}" rel="stylesheet">
    {% block stylesheet %}{% endblock %}
</head>

<body>
{% block body %}
    <nav class="navbar navbar-expand-md navbar-dark bg-primary py-2 navbar-fixed-top fixed-top">
        <a class="navbar-brand py-0 font-weight-bold" href="{% url 'appointment:home' %}">
            جلس (دانشگاه تهران)
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarsExampleDefault"
                aria-controls="navbarsExampleDefault" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            {% block navbar_collapse %}

            {% endblock %}

            {% block nav_panel %}
                {% if user.is_authenticated %}
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active dropdown mx-0 mx-md-2 my-3">
                            {{ user.get_full_name }}
                        </li>
                        <li class="nav-item active dropdown mx-0 mx-md-1 my-1">
                            <a href="{% url 'accounts:logout' %}"
                               class="nav-link btn-secondary text-primary">خروج</a>
                        </li>
                        <li class="nav-item active dropdown mx-0 mx-md-1 my-1">
                            <a href="{% url 'accounts:notification-policy' %}"
                               class="nav-link btn-secondary text-primary">سیاست اعلان</a>
                        </li>
                    </ul>
                {% else %}
                    <form method="post" action="{% url 'accounts:login' %}?next={{ request.path }}"
                          novalidate>
                        {#                        {% csrf_token %}#}
                        <ul class="navbar-nav">
                            <li class="nav-item mx-0 mx-md-1 my-1"><a
                                    class="btn btn-secondary nav-link text-primary"
                                    href="{% url 'accounts:register' %} " role="button">ثبت
                                نام</a>

                            </li>
                            <li class="nav-item dropdown mx-0 mx-md-1 my-1">
                                <a class="nav-link dropdown-toggle btn btn-secondary text-primary"
                                   id="dropdown02"
                                   data-toggle="dropdown"
                                   aria-haspopup="true"
                                   aria-expanded="false">ورود به حساب کاربری</a>
                                <div class="dropdown-menu right-dropdown p-3"
                                     aria-labelledby="dropdown02">
                                    <div class="form-group">
                                        <label for="id_username">نام کاربری</label>
                                        <input type="text" name="username" autofocus
                                               class="form-control" required
                                               id="id_username">
                                        <label for="id_password">گذرواژه</label>
                                        <input type="password" name="password"
                                               class="form-control" required
                                               id="id_password">
                                    </div>

                                    <button type="submit"
                                            class="m-auto w-50 btn-block btn btn-success">ورود
                                    </button>
                                </div>
                            </li>
                        </ul>
                    </form>
                {% endif %}
            {% endblock %}
        </div>
    </nav>

    <main role="main" class="container-fluid mb-5 pt-4 px-lg-5 wrapper text-primary">

    {% block container %}

        <div class="my-md-2 pb-3">
            {% if messages %}
                {% for message in messages %}
                    <div class="card p-4 text-light {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}bg-danger{% else %}bg-success{% endif %}">
                        {{ message }}<br>
                    </div>
                {% endfor %}
                </div>
            {% endif %}
        <h1 class="h2">{% block card_header %}{% endblock %}</h1>
        <div class="dropdown-divider mb-md-2"></div>
        {% block card_body %}

        {% endblock %}
    {% endblock %}


    {% block modal %}
        <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title text-center ml-auto" id="modalLabel">
                            {% block modal_title %}
                                جلس{% endblock %}</h5>
                        <button type="button" class="close" data-dismiss="modal"
                                aria-label="Close">
                            <small class="small"><span class="fa fa-times"></span></small>
                        </button>
                    </div>
                    <div class="modal-body text-center text-black rtl">
                        {% block modal_body %}

                        {% endblock %}
                    </div>
                    <div class="modal-footer" id="modal-btn-div">
                        {% block modal_buttons %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
{% endblock %}
<div class="push"></div>
</main>

<footer class="footer text-center text-white bg-primary py-3 small">
    کلیه‌ حقوق این سامانه متعلق به دانشگاه تهران است. ©
</footer>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/http_cdnjs.cloudflare.com_ajax_libs_popper.js_1.14.3_umd_popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-128397229-2"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-128397229-2');
</script>
{% block scripts %}{% endblock %}

<link rel="stylesheet"
      href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>

</body>
</html>

templates/event.html
{% block event %}
    <ul>
        {% for appointment in appointments %}
            <li>
                <a href="{% url 'appointment:detail'  appointment.id %}">{{ appointment.poll.title }} </a>
            </li>
        {% empty %}
            <li class="text-secondary"> جلسه ای ایجاد نشده است</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/form-template.html
{#{{ form }}#}
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
              <span class="text-danger small">
                  {{ field.errors }}
              </span>
        </div>
        {#        field.label_tag#}
        <label class="control-label col-sm-2"> {{ field.label_tag }}  </label>
        <div class="col-sm-10">{{ field }}</div>

    </div>
{% endfor %}