appointment/urls.py
from django.urls import path

from appointment.views import IndexView, IndexViewOld, DetailView, CreateFromPoll, \
    CancelAppointmentView, PollInvitationCreateView, PollInvitationDeleteView

app_name = 'appointment'
urlpatterns = [
    path('home/', IndexView.as_view(), name='home'),
    path('cancel-appointment/<int:pk>/', CancelAppointmentView.as_view(),
         name='cancel-appointment'),
    path('old/', IndexViewOld.as_view(), name='old'),
    path('<int:pk>/', DetailView.as_view(), name='detail'),
    path('from-polls/', CreateFromPoll.as_view(), name='create-from-poll'),
    path('poll-invitations/create/<int:pk>/', PollInvitationCreateView.as_view(),
         name='create-poll-invitation'),
    path('poll-invitations/delete/<int:pk>/', PollInvitationDeleteView.as_view(),
         name='delete-poll-invitation'),
]

jalas/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('appointment/', include('appointment.urls')),
    path('reservation/', include('reservation.urls')),
    path('monitoring/', include('monitoring.urls')),
    prefix_default_language=False)

reservation/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from reservation.views import PollDetailsView, AvailableRoomsView, \
    PollCreateView, VoteCreateView, CancelPollView, CommentsView, \
    AddItem, CommentsViewUpdate, CommentsViewDelete, PollItemDelete, ReplyCreateView

app_name = 'reservation'
urlpatterns = [
    path('polls/<int:pk>/cancel/', CancelPollView.as_view(), name='cancel-poll'),
    path('polls/<int:pk>/comments/', CommentsView.as_view(), name='poll-comments'),
    path('polls/<int:pk>/', PollDetailsView.as_view(), name='poll-details'),
    path('polls/<int:pk>/additem/', AddItem.as_view(), name='add-item'),
    path('polls/new/', PollCreateView.as_view(), name='poll-create'),
    path('<int:pk>/cancel/', PollItemDelete.as_view(), name='poll-item-delete'),
    path('available-rooms/', AvailableRoomsView.as_view()),
    path('<uuid:uuid>/', csrf_exempt(VoteCreateView.as_view()), name='vote-details'),
    path('comment-edit/<int:pk>/', CommentsViewUpdate.as_view(), name='comment-update'),
    path('comment-delete/<int:pk>/', CommentsViewDelete.as_view(), name='comment-delete'),
    path('reply-create/<int:pk>/', ReplyCreateView.as_view(), name='reply-create'),
]

reservation/models.py
import re
from datetime import datetime

from django.db import models
from django.template.loader import render_to_string
from django.utils import timezone

from accounts.models import User
from reservation import facade
from reservation.enums import PollStateChoices, VoteStateChoices
from utilities import mail_sender


class Poll(models.Model):
    title = models.CharField(max_length=100, verbose_name='عنوان')
    created_at = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_polls')
    last_retrieved_at = models.DateTimeField(blank=True, null=True)
    state = models.CharField(choices=PollStateChoices, max_length=40,
                             default='WAITING_FOR_VOTE')
    deadline = models.DateTimeField()

    def __str__(self):
        return self.title

    def is_cancelled(self):
        return self.state == 'CANCELLED'

    def has_appointment(self):
        return hasattr(self, 'appointment')


class PollItem(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    date = models.DateField()
    start_at = models.TimeField()
    end_at = models.TimeField()

    class Meta:
        unique_together = ['poll', 'start_at', 'end_at', 'date']

    def __str__(self):
        return f'{self.poll.title} {self.date} {self.start_at} - {self.end_at}'

    def delete(self, using=None, keep_parents=False):
        facade.on_item_delete(self)
        super().delete(using, keep_parents)

    @property
    def start(self):
        return datetime.combine(self.date, self.start_at)

    @property
    def end(self):
        return datetime.combine(self.date, self.end_at)

    def agreed_votes(self):
        return self.vote_set.filter(state='yes')

    def disagreed_votes(self):
        return self.vote_set.filter(state='no')

    def abstainer_votes(self):
        return self.vote_set.filter(state='abstainer')


class Vote(models.Model):
    invitation = models.ForeignKey('appointment.PollInvitation', on_delete=models.CASCADE)
    state = models.CharField(choices=VoteStateChoices, max_length=32)
    poll_item = models.ForeignKey(PollItem, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['poll_item', 'invitation']


class Room:
    def __init__(self, number):
        self.number = number


class Comment(models.Model):
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    poll = models.ForeignKey('reservation.Poll', on_delete=models.CASCADE, blank=True, null=True)
    text = models.CharField(max_length=256)
    created_at = models.DateTimeField(default=timezone.now)
    root_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def save(self, *args, **kwargs):
        self._notify_mentioned_people()
        return super().save(*args, **kwargs)

    def get_root_poll(self):
        return self.poll or self.root_comment.get_root_poll()

    def get_safe_text(self) -> str:
        return re.sub(r'([\w.-]+@[\w.-]+)', r'<a href="#" class="text-info">\1</a>', self.text)

    def _extract_mentioned_emails(self):
        return re.findall(r'[\w.-]+@[\w.-]+', self.text)

    def _notify_mentioned_people(self):
        from appointment.models import PollInvitation

        for email in self._extract_mentioned_emails():
            invitation = PollInvitation.objects. \
                filter(poll=self.get_root_poll(), user__email=email). \
                filter(user__mention_notification=True).first()
            if invitation is None:
                continue
            rendered_email = render_to_string('emails/mention_notification.html',
                                              context={'comment': self, 'invitation': invitation})
            mail_sender.send_email('منشن شدید', rendered_email, [email])

reservation/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.db import transaction
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.views import View
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from rest_framework.status import HTTP_500_INTERNAL_SERVER_ERROR

from appointment.forms import PollInvitationFormSet
from appointment.models import PollInvitation, Appointment
from reservation import facade
from reservation.exceptions import LogicException
from reservation.models import Poll, PollItem, Vote, Comment
from utilities import mail_sender
from .forms import PollItemFormSet, AddItemFormSet, PollCreateForm


class AddItem(PermissionRequiredMixin, View):
    def has_permission(self):
        self.poll = get_object_or_404(Poll, pk=self.kwargs.get('pk'))
        return self.request.user.is_authenticated

    def post(self, request, *args, **kwargs):
        formset = AddItemFormSet(request.POST, instance=self.poll)
        if formset.is_valid():
            added_poll_items = formset.save()
            facade.notify_poll_item_adds(added_poll_items)
            return redirect(reverse('reservation:poll-details', kwargs={'pk': self.poll.pk}))
        messages.error(request, 'لطفا خطاهای زیر را یرطرف کنید!')
        return render(request, 'reservations/poll_details_view.html', context={
            'poll': self.poll,
            'poll_items': formset
        })


class PollItemDelete(PermissionRequiredMixin, DeleteView):
    model = PollItem

    def has_permission(self):
        poll_item = get_object_or_404(PollItem, pk=self.kwargs.get('pk'))
        return self.request.user == poll_item.poll.creator

    def get(self, request, *args, **kwargs):
        messages.success(request, 'گزینه‌ی مورد نظر با موفقیت حذف شد')
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('reservation:poll-details', kwargs={'pk': self.object.poll_id})


class PollDetailsView(PermissionRequiredMixin, DetailView):
    template_name = 'reservations/poll_details_view.html'
    model = Poll
    context_object_name = 'poll'

    def has_permission(self):
        obj = self.get_object()
        allowed_user_ids = list(obj.invitations.values_list('user', flat=True))
        return self.request.user.id in allowed_user_ids

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj and not hasattr(obj, 'appointment'):
            obj.last_retrieved_at = timezone.now()
            obj.save()
        return obj

    def get_context_data(self, **kwargs):
        obj = self.get_object()
        context = super().get_context_data(**kwargs)
        context['can_comment'] = not obj.has_appointment() and not obj.is_cancelled()
        context['poll_items'] = AddItemFormSet()
        context['editable'] = context['can_comment'] and self.request.user == obj.creator
        return context


class CommentsView(PermissionRequiredMixin, CreateView):
    model = Comment
    fields = ['text']

    def get_success_url(self):
        return reverse('reservation:poll-details', kwargs={'pk': self.object.poll.pk})

    def has_permission(self):
        poll = get_object_or_404(Poll, pk=self.kwargs['pk'])
        return self.request.user.id in list(poll.invitations.values_list('user', flat=True))

    def form_valid(self, form):
        form.instance.poll_id = self.kwargs['pk']
        form.instance.user = self.request.user
        return super().form_valid(form)


class CommentsViewUpdate(PermissionRequiredMixin, UpdateView):
    model = Comment
    fields = ['text']
    template_name = 'reservations/edit_comment.html'

    def has_permission(self):
        comment = get_object_or_404(Comment, pk=self.kwargs['pk'])
        return self.request.user == comment.user

    def post(self, request, *args, **kwargs):
        messages.success(request, 'نظر شما بازنگری شد')
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('reservation:poll-details', kwargs={'pk': self.object.get_root_poll().pk})


class CommentsViewDelete(PermissionRequiredMixin, DeleteView):
    model = Comment

    def has_permission(self):
        comment = get_object_or_404(Comment, pk=self.kwargs['pk'])
        return self.request.user == comment.user

    def get(self, request, *args, **kwargs):
        messages.success(request, 'نظر شما حذف شد')
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('reservation:poll-details', kwargs={'pk': self.object.poll_id})


class ReplyCreateView(PermissionRequiredMixin, CreateView):
    model = Comment
    fields = ['text']
    template_name = 'reservations/reply_create_view.html'

    def has_permission(self):
        self.root_comment = get_object_or_404(Comment, id=self.kwargs['pk'])
        allowed_user_ids = list(
            self.root_comment.get_root_poll().invitations.values_list('user', flat=True))
        return self.request.user.id in allowed_user_ids

    def form_valid(self, form):
        form.instance.root_comment = self.root_comment
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['root_comment'] = self.root_comment
        return context

    def get_success_url(self):
        messages.success(self.request, 'با موفقیت ریپلای کردید')
        return reverse('reservation:poll-details', kwargs={'pk': self.object.get_root_poll().id})


class AvailableRoomsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        poll_item_id = request.GET.get('poll_item_id')
        poll_item = get_object_or_404(PollItem, id=poll_item_id)
        try:
            rooms = facade.fetch_available_rooms(poll_item.start, poll_item.end)
        except LogicException as e:
            return JsonResponse(status=HTTP_500_INTERNAL_SERVER_ERROR, data={
                'err': e.msg
            })

        return JsonResponse(data={
            'rooms': [room.number for room in rooms]
        })


class PollCreateView(CreateView):
    model = Poll
    form_class = PollCreateForm
    template_name = 'reservations/poll_create_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['poll_items'] = PollItemFormSet(self.request.POST)
            context['poll_invitations'] = PollInvitationFormSet(self.request.POST)
        else:
            context['poll_items'] = PollItemFormSet()
            context['poll_invitations'] = PollInvitationFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        poll_items = context['poll_items']
        invitations = context['poll_invitations']
        with transaction.atomic():
            form.instance.creator = self.request.user
            self.object = form.save()
            if poll_items.is_valid() and invitations.is_valid():
                poll_items.instance = self.object
                poll_items.save()
                invitations.instance = self.object
                invitations.save()
                try:
                    PollInvitation.objects.get_or_create(user=self.request.user, poll=self.object)
                except Exception:
                    pass
            else:
                return self.form_invalid(form)
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, 'نظرستجی با موفقیت ایجاد شد!')
        return reverse('reservation:poll-details', kwargs={'pk': self.object.pk})


class VoteCreateView(View):
    def get(self, request, uuid):
        invitation = get_object_or_404(PollInvitation, uuid=uuid)
        login(request, invitation.user)
        if invitation.poll.has_appointment():
            return HttpResponseRedirect(
                reverse('reservation:poll-details', kwargs={'pk': invitation.poll_id}))
        return render(request, 'reservations/vote_create_view.html', context={
            'poll': invitation.poll,
            'votes': invitation.vote_set.all(),
        })

    @transaction.atomic
    def post(self, request, uuid):
        invitation = get_object_or_404(PollInvitation, uuid=uuid)
        if hasattr(invitation.poll, 'appointment'):
            return HttpResponseRedirect(reverse('reservation:poll-details'))

        if not self._data_is_valid(invitation):
            messages.error(request, 'برای هر ردیف باید نظر خود را ثبت کنید')
            return render(request, 'reservations/vote_create_view.html', context={
                'poll': invitation.poll
            })
        self._create_new_votes(invitation)
        messages.success(request, 'نظر شما ثبت شده است. منتظر قطعی شدن جلسه بمانید.')
        return self.get(request, uuid)

    @staticmethod
    def _notify_creator(votes, invitation):
        if not invitation.poll.creator.vote_add_notification:
            return
        rendered_email = render_to_string('emails/votes_notification.html', context={
            'votes': votes
        })
        mail_sender.send_email('ثبت رای جدید', rendered_email, [invitation.poll.creator.email])

    def _data_is_valid(self, invitation):
        given_item_ids = sorted([int(key) for key in dict(self.request.POST)])
        required_item_ids = sorted(list(invitation.poll.pollitem_set.values_list('id', flat=True)))
        print('given_item_ids: ', given_item_ids)
        print('required_item_ids: ', required_item_ids)

templates/reservations/comments_includable.html
<ul>
    {% for comment in comments %}
        <li>
            {{ comment.user.get_full_name }}
            گفت:
            {{ comment.get_safe_text|safe }}
            <a href="{% url 'reservation:reply-create' comment.id %}">
                <i class="fa fa-reply text-success ml-5 mr-5"></i>
            </a>
            {% if comment.user == request.user %}
                <a href="{% url 'reservation:comment-update' comment.id %}">
                    <i class="fa fa-edit text-info ml-5"></i>
                </a>
                <a href="{% url 'reservation:comment-delete' comment.id %}">
                    <i class="fa fa-times text-danger"></i>
                </a>
            {% endif %}
            {% with comments=comment.comment_set.all %}
                {% include 'reservations/comments_includable.html' %}
            {% endwith %}
        </li>
    {% endfor %}
</ul>

templates/reservations/edit_comment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block  container %}
    <form method="post" class="mb-4">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">اعمال تغیرات</button>
    </form>
{% endblock %}

templates/reservations/poll_create_view.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}


{% block title %}
    ایجاد نظرسنجی
{% endblock %}

{% block card_header %}
    ایجاد نظرسنجی
{% endblock %}


{% block card_body %}
    <form action="" method="post">{% csrf_token %}
        {{ form|crispy }}
        <br><br>
        <h4>گزینه‌های حضور</h4>
        {% with formset=poll_items  prefix='pollitem_set' %}
            {% include 'includes/formset.html' %}
        {% endwith %}
        <h4>مدعوین</h4>
        {% with formset=poll_invitations prefix='invitations' %}
            {% include 'includes/formset.html' %}
        {% endwith %}

        <button type="submit" class="btn btn-success">ایجاد نظرسنجی</button>
    </form>
{% endblock %}

templates/reservations/poll_details_view.html
{% extends 'base.html' %}
{% load static jformat %}
{% load static crispy_forms_tags %}

{% block scripts %}
    <script src="{% static 'js/empty_rooms_ajax.js' %}" type="application/javascript"></script>
    <script src="{% static 'js/reserve_room_ajax.js' %}" type="application/javascript"></script>
{% endblock %}

{% block title %}
    {{ poll.title }}
{% endblock %}

{% block card_header %}
    {{ poll.title }}
    <br>
    {% if editable %}
        <a class="h5 text-danger" href="{% url 'reservation:cancel-poll' poll.id %}">
            لغو نظرسنجی
        </a>
    {% endif %}

    {% if poll.has_appointment and not poll.appointment.is_cancelled %}
        <a class="h5 text-danger"
           href="{% url 'appointment:cancel-appointment' poll.appointment.id %}">
            لغو جلسه
        </a>
    {% endif %}
    <h5 class="text-muted">
        ایجاد شده توسط
        {{ poll.creator.get_full_name }}
        در:
    </h5>
    <h5 class="text-muted">
        <i class="fas fa-calendar"></i>
        {{ poll.created_at|jformat:'%Y/%-m/%-d' }}
    </h5>
    <h5 class="text-muted">
        <i class="fas fa-clock"></i>
        {{ poll.created_at|jformat:'%H:%M' }}
    </h5>
{% endblock %}

{% block card_body %}
    <h3>
        مدعوین
        ({{ poll.invitations.distinct.count }})
        {% if editable %}
            <a href="{% url 'appointment:create-poll-invitation' poll.id %}"
               class="h5 text-secondary">
                دعوت از فرد جدید
            </a>
        {% endif %}
    </h3>
    <ul>
        {% for invitee in poll.invitations.distinct %}
            <li>
                {% if editable %}
                    <a href="{% url 'appointment:delete-poll-invitation' invitee.id %}">
                        <i class="fa fa-times text-danger"></i>
                    </a>
                {% endif %}
                {{ invitee.user.get_full_name }}
            </li>
        {% endfor %}
    </ul>

    {% if editable %}
        <form method="post" action=" {% url 'appointment:create-from-poll' %}"
              id="create_from_poll">
        {% csrf_token %}
    {% endif %}

{% if poll.is_cancelled %}
    این نظرسنجی لغو شده است
{% endif %}
{% if poll.appointment.is_cancelled %}
    این جلسه لغو شده است
{% endif %}
<ul class="list-group">
    {% for poll_item in poll.pollitem_set.all %}
        <li class="list-group-item my-3">
            <div class="row">
                <div class="col-1">
                    {% if editable %}
                        <div class="custom-checkbox custom-control form-check">
                            <input type="radio" name="poll_item"
                                   class="custom-control-input js-poll-item"
                                   value="{{ poll_item.id }}"
                                   id="input_{{ poll_item.id }}">
                            <label class="custom-control-label" for="input_{{ poll_item.id }}">
                                &nbsp;
                            </label>
                        </div>
                    {% elif poll.appointment.poll_item == poll_item %}
                        <h2 class="fas fa-check-circle text-success"></h2>
                    {% else %}
                        <h2 class="fas fa-times-circle text-danger"></h2>
                    {% endif %}

                </div>
                <div class="col-2">
                    {{ poll_item.date|jformat:'%Y/%-m/%-d' }}
                </div>

                <div class="col-2">
                    {{ poll_item.start_at.isoformat }} -
                    {{ poll_item.end_at.isoformat }}
                </div>

                <div class="col-2">
                    تعداد موافقین: {{ poll_item.agreed_votes.count }}
                </div>

                <div class="col-2">
                    تعداد مخالفین: {{ poll_item.disagreed_votes.count }}
                </div>
                <div class="col-2">
                    تعداد ممتنعین: {{ poll_item.abstainer_votes.count }}
                </div>
                {% if poll.creator == request.user %}
                    <a href="{% url 'reservation:poll-item-delete' poll_item.id %}">
                        <i class="fa fa-times text-danger"></i>
                    </a>
                {% endif %}
            </div>
        </li>
    {% endfor %}

</ul>
<hr>
<h3>نظرات</h3>
<ul>
    {% for comment in poll.comment_set.all %}
        <li>
            {{ comment.user.get_full_name }}
            گفت:
            {{ comment.get_safe_text|safe }}
            <a href="{% url 'reservation:reply-create' comment.id %}">
                <i class="fa fa-reply text-success ml-5 mr-5"></i>
            </a>
            {% if comment.user == request.user %}
                <a href="{% url 'reservation:comment-update' comment.id %}">
                    <i class="fa fa-edit text-info ml-5"></i>
                </a>
                <a href="{% url 'reservation:comment-delete' comment.id %}">
                    <i class="fa fa-times text-danger"></i>
                </a>
            {% endif %}
            {% with comments=comment.comment_set.all %}
                {% include 'reservations/comments_includable.html' %}
            {% endwith %}
        </li>
    {% empty %}
        نظری ثبت نشده است
    {% endfor %}
</ul>
{% if editable %}
    <label for="room_list">انتخاب اتاق:</label>
    <span class="fa-spinner fa-spin fas" id="room_list_loading" hidden></span>
    <select id="room_list" class="form-control bg-info text-light" name="room_number">
        <option>ابتدا یکی زمان‌های بالا را انتخاب کنید!</option>
    </select>

    <button type="submit" class="mt-3 btn btn-success" id="submit_button" disabled>
        ایجاد
    </button>

    <a class="mt-3 btn btn-danger" id="cancel_btn" href="cancel/" hidden>
        لغو جلسه
    </a>
    <span class="fa-spinner fa-spin fas" id="submit_loading" hidden></span>
    </form>

{% endif %}
    {% if can_comment %}
        <form method="post" action="{% url 'reservation:poll-comments' poll.pk %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="comment-text">ثبت نظر</label>
                <textarea type="text" id="comment-text" class="form-control" name="text" required>
            </textarea>
            </div>
            <button class="btn btn-success">ثبت نظر</button>
        </form>
    {% endif %}
    {% if editable %}
        <form method="post" action="{% url 'reservation:add-item' poll.pk %}">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <label for="comment-text">ویرایش</label>
                <h4>گزینه‌های حضور</h4>
                {% with formset=poll_items %}
                    {% include 'includes/formset.html' %}
                {% endwith %}
            </div>
            <button class="btn btn-success">ویرایش</button>
        </form>'

    {% elif not poll.is_cancelled and poll.has_appointment and not poll.appointment.is_cancelled %}
        <h3>مکان</h3>
        اتاق {{ poll.appointment.room_number|default:'نامشخص' }}
        <h3>زمان</h3>
        {{ poll.appointment.poll_item }}
    {% endif %}

{% endblock %}

templates/reservations/reply_create_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block card_header %}
    پاسخ به نظر
{% endblock %}

{% block  card_body %}
    <h4>نظر اصلی</h4>
    {{ root_comment.user.get_full_name }}: {{ root_comment.text }}<br>
    <form method="post" class="mb-4">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">اعمال تغیرات</button>
    </form>
{% endblock %}

templates/reservations/vote_create_view.html
{% extends 'base.html' %}

{% block title %}
    ثبت رای
{% endblock %}

{% block card_header %}
    ثبت رای
    <br>
    {{ poll.title }}
{% endblock %}


{% block card_body %}
    <a href="{% url 'reservation:poll-details' poll.id %}">
        مشاهده جزئیات بیشتر
    </a>
    <form method="post" class="">
        {% if not poll.has_appointment and votes.count == 0 %}
            <h4>گزینه‌ها</h4>
            {% for poll_item in poll.pollitem_set.all %}
                {% include 'reservations/votes_includable.html' %}
            {% endfor %}
            <button type="submit" class="btn btn-success">ثبت رای</button>
        {% elif votes.count > 0 %}
            <h3>شما رای خود را ثبت کرده‌اید</h3>
            نام شما:
            {{ votes.0.name }}
            <br>
            {% for vote in votes %}
                {% include 'reservations/votes_includable.html' with poll_item=vote.poll_item state=vote.state %}
            {% endfor %}
            <button type="submit" class="btn btn-success">به روزرسانی رای</button>
        {% endif %}
    </form>
{% endblock %}

templates/reservations/votes_includable.html
{% load jformat %}

<div class="form-group">
    {{ poll_item.date|jformat:'%Y/%-m/%-d' }}
    از ساعت
    {{ poll_item.start_at|jformat:'%H:%M' }}
    تا
    {{ poll_item.end_at|jformat:'%H:%M' }}

    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="{{ poll_item.id }}" value="yes"
                   {% if state == "yes" %}checked{% endif %}>
            موافق
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="{{ poll_item.id }}" value="no"
                   {% if state == "no" %}checked{% endif %}>
            مخالف
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="{{ poll_item.id }}"
                   value="abstainer" {% if state == "abstainer" or not state %}checked{% endif %}>
            نظری ندارم
        </label>
    </div>
</div>